spring:
  application:
    name: ms-pagamento
  cloud:
    openfeign:
      client:
        config:
          mercadopago:
            default-request-headers:
              Authorization:
                - Bearer TEST-6416668675808261-012515-7dac31f086dd3bdf5d7137ace77d0ad1-1654958216
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/pagamentos?authSource=admin
      database: pagamentos
      
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: ${QUEUE_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 5000
          max-interval: 300000
          multiplier: 3

server:
  port: 8081
  
rest:
  service:
    mercadopago:
      url: https://api.mercadopago.com
      user-id: 1654958216
      pos-id: FIAP001POS001
      notification-url: "https://9ce8-187-19-179-207.ngrok-free.app/v1/pedidos/confirmar-pagamento"
    ms-pedido:
      url: http://localhost:8080
      context: api/v1

assets:
  image: "qr-codes/qrcode-pedido-"
  
queue:
  filas:
    pedidos_criados: pedidos_criados
    pagamentos_nao_gerados: pagamentos_nao_gerados-dlq
    pagamentos_confirmados: pagamentos_confirmados
  exchange:
    fanoutPedido: pedidos.ex
    fanoutPagamento: pagamento.ex
    deadLetterPedido: pagamentos.dlx